### ISSUE TITLE
[Implemented] Request for additional currencies in the InvoiceCurrency enum

### ISSUE THREAD

**Issue by MorneSaunders360** [Codeh4ck/InvoiceSdk#1]
I am using the InvoiceCurrency enum in the NuGet package and would like to request the addition of more currencies to better support my project's requirements. Specifically, I need support for the following currencies: [South African Rand].

These additional currencies are necessary for accurately representing the currencies used in my project's invoicing system. Including them in the enum would greatly benefit the usability and functionality of the package for my use case.

**Comment by Codeh4ck** [comment]
List the currencies (currency code) you would like to include and I will update the library as soon as I can.

@MorneSaunders360

**Comment by MorneSaunders360** [comment]
I would like to have South African Rand added Currency Code (ZAR).

**Comment by Codeh4ck** [comment]
Version 1.2.0 supports South African Rand now alongside .NET 8. Please note that there is a slight update on how PDFs are saved due to QuestPDF licensing issues. Feel free to open a new issue if you encounter any problems or want additional functionality.

Check the Example project for reference: on new save way: https://github.com/Codeh4ck/InvoiceSdk/commit/ef1d4e3276f3c06a273c01f394b848b3364a79bb
